[package]
name = "techworld-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.3", features = ["mysql", "r2d2"] }
serde = { version = "1.0.94", features = ["derive"] }